### PR TITLE
Move to maven central

### PR DESCRIPTION
**Pull request by muuki88**
Maven Central access: https://issues.sonatype.org/browse/OSSRH-68549

### CODE REVIEW

**Comment by muuki88** [comment]
Requires a change of maven coordinates as `rocks.muki` is harder to get :P

**Comment by felixbr** [comment]
What do you mean it's harder to get? Thought it was your domain? :D

**Comment by muuki88** [comment]
Yeah... But it's hosted via GitHub through Cloudflare to get HTTPS and the domain belongs to my other Webspace provider...

And password reset for Cloudflare was so slow, I gave up. 

And the .rocks domain is not that ideal. Especially email doesn't work properly

**Comment by muuki88** [comment]
I regret my muki.rocks domain in general 😅😅

**Comment by felixbr** [comment]
I see. I personally use `felixbr.github.io`. It's boring and I haven't tested email but at least it doesn't need any maintenance on my part.

**Pull request merged**
