### PR TITLE
Added JsonCodeGen for play-json

### PR DESCRIPTION
**Pull request by chorandrey**
Hi @muuki88 
Thanks for your project. I added play-json implementation for code generator. Hope it also will be useful.

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks @chorandrey for your time and work :heart: 

In order to merge this pull request a few things are missing :smile: 

- Add a sbt integration similar to the [apollo-circe tests](https://github.com/muuki88/sbt-graphql/tree/master/src/sbt-test/codegen/apollo-circe)
- Add a note to [the JsonSupport section in the Readme](https://github.com/muuki88/sbt-graphql#json-support)
- Fix the `scalafmt` issues by running `scalafmt` :sunglasses:

**Comment by chorandrey** [comment]
Yep, I'm taking it to work

**Comment by muuki88** [comment]
Awesome, thanks :smiley: 

If you need any help with the sbt tests, feel free to ask :)

**Comment by chorandrey** [comment]
Tests will be a little challenge for me (and can take few days), but at the moment I would ask following:
- are scala sources in `src\test\resources\apollo\starwars-circe` should be written manually ?
- I couldn't find so far where and how `src/sbt-test/codegen/apollo-circe` is used. Is there is any specific sbt task for it? And is it separate sbt project which should be ran from it's directory?

**Comment by muuki88** [comment]
> are scala sources in src\test\resources\apollo\starwars-circe should be written manually ?

Yes. What I recommend is copying the `starwars-circe` folder and adapt each test.

> I couldn't find so far where and how `src/sbt-test/codegen/apollo-circe` is used

These are [sbt scripted tests|https://www.scala-sbt.org/1.0/docs/Testing-sbt-plugins.html]. You can run them all with `sbt scripted` or select specific ones with `sbt "scripted code-gen/*"` or `sbt "scripted code-gen/apollo-circe"`

**Comment by muuki88** [comment]
Any news on this one @chorandrey :smile:

**Pull request closed without merging**
