### PR TITLE
Fixes #65

### LINKED ISSUE #65: codegen support for 'URI' scalar type
Alias URI to String.

### PR DESCRIPTION
**Pull request by NicolasRouquette**

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks for your pull request :hugs: 

Is this a custom type in your code base? If so then you should solve this by importing the required types with `graphqlCodegenImports`. See https://github.com/muuki88/sbt-graphql#scalar-types

**Comment by NicolasRouquette** [comment]
The github schema defines a scalar type: `URI`.
With `graphqlCodegenImports += "java.net.URI"`, I get errors because there is no circe decoder available.

Perhaps this could be remedied with another import.
For the time being, the simplest is to handle `URI` just like `ID`, i.e., as an alias to `String`.

**Comment by muuki88** [comment]
I understand your intention, but adding types from a specific schema into the generic code generation is IMHO not good solution as this may break others that actually have a valid `URI` type and types for it.

What should work is the following

```scala
package com.github.graphql

object types {
   type URI = String
}
```

in your `build.sbt`

```sbt
graphqlCodegenImports += "com.github.graphql.types._"
```

WDYT?

**Comment by muuki88** [comment]
Closing this. We shouldn't add magic behaviour for random types. If there's a better way to handle these scenarios than the current options, I'm open for suggestions and pull requests :)

**Pull request closed without merging**
