### PR TITLE
Fixes #61

### LINKED ISSUE #61: jawn parser library incompatibility
With sbt 1.2.8, I'm running into a library conflict with jawn parser similar to this:
https://stackoverflow.com/questions/47227060/ammonite-classpath-clashes-with-github4s-java-lang-abstractmethoderror

Except for different URLs, the `build.sbt` is similar to the doc:

```
graphqlSchemas += GraphQLSchema(
  "sangria-example",
  "staging schema at http://try.sangria-graphql.org/graphql",
  Def.task(
    GraphQLSchemaLoader
      .fromIntrospection("http://try.sangria-graphql.org/graphql", streams.value.log)
      .loadSchema()
  ).taskValue
)
```

The stack trace is this:

```
[error] java.lang.AbstractMethodError
[error] 	at jawn.CharBasedParser.parseString(CharBasedParser.scala:90)
[error] 	at jawn.CharBasedParser.parseString$(CharBasedParser.scala:87)
[error] 	at jawn.StringParser.parseString(StringParser.scala:15)
[error] 	at jawn.Parser.rparse(Parser.scala:428)
[error] 	at jawn.Parser.parse(Parser.scala:338)
[error] 	at jawn.SyncParser.parse(SyncParser.scala:24)
[error] 	at jawn.SupportParser.$anonfun$parseFromString$1(SupportParser.scala:15)
[error] 	at jawn.SupportParser.parseFromString(SupportParser.scala:15)
[error] 	at jawn.SupportParser.parseFromString$(SupportParser.scala:14)
[error] 	at io.circe.jawn.CirceSupportParser$.parseFromString(CirceSupportParser.scala:7)
[error] 	at io.circe.jawn.JawnParser.parse(JawnParser.scala:16)
[error] 	at io.circe.parser.package$.parse(package.scala:8)
[error] 	at rocks.muki.graphql.schema.IntrospectSchemaLoader.introspect(SchemaLoader.scala:118)
[error] 	at rocks.muki.graphql.schema.IntrospectSchemaLoader.loadSchema(SchemaLoader.scala:85)
```

In Intellij, I see that under `External Libraries`, there is an entry for `sbt: sbt-and-plugins`.
In there, there are indeed two versions of jawn parser:

`jawn-parser_2.12-0.10.4.jar` (from SBT itself)
`jawn-parser_2.12-0.11.1.jar` (from `circe-jawn`)

It is unclear how to resolve this library conflict.

### PR DESCRIPTION
**Pull request by NicolasRouquette**

### CODE REVIEW

**Comment by Krever** [comment]
Hey @muuki88 @NicolasRouquette 
It seems that sangria lost its main maintainer some time ago so it might take a while for the https://github.com/sangria-graphql/sangria-circe/pull/14 to be merged. 

Do you think we could merge and release this as a workaround? 
Or maybe there is any other workaround for #61?

**Comment by NicolasRouquette** [comment]
@muuki88 The dependencies on circe & jawn are tricky because they happen in two different contexts:

- in the sbt-graphql plugin itself -- these dependencies affect the plugin code at compilation time
- in the project's build.sbt -- these dependencies affect the plugin code at runtime

The problem here is when the project's dependencies load versions of dependencies (circe, jawn, ...) that are not binary compatible with the versions of the dependencies used at compile time.

Shading avoids this problem because it makes a copy of the compile-time dependencies to use at runtime.

Whether to go with this or not depends on how whether the circe & jawn dependencies will have binary incompatibilities in the future or not. At this time, there *is* a binary incompatibility that will affect some unsuspecting users so I suggest to keep shading.

@Krever I've been using my fixed version since I submitted the PR.

To do this, I merged my fix (https://github.com/NicolasRouquette/sbt-graphql/tree/issue-61) into my fork's master branch (https://github.com/NicolasRouquette/sbt-graphql/tree/master) that I had updated w.r.t. upstream master. The short SHA1 on my fork's master is: 14b2afe

Thanks to git versioning, publishing locally yields version: 0.12.0-14b2afe

This can be used locally like this:

```
addSbtPlugin("rocks.muki" % "sbt-graphql" % "0.12.0-14b2afe")
```

Since circe & jawn dependencies are shaded, it doesn't really matter which versions of these libraries the project uses; the sbt-graphql plugin uses its private shaded copy.

**Comment by muuki88** [comment]
I would rather not merge this PR as this is way to complex for a simple plugin as this.

Is there a possibility to remove jawn completely as a parser and use something else?

**Comment by muuki88** [comment]
I saw that circe has a jackson module as well. I'm totally fine with using that instead of jawn.

**Pull request closed without merging**
